### ISSUE TITLE
Generate Sprite sheet can not work in blender 4.2

### ISSUE THREAD

**Issue by chen649285912** [PurgatoryMP/Sequenced_Bake#1]
Although it shows that it has been generated normally, it is not actually generated, and no generated pictures pop up automatically, and it cannot be found in the folder

https://github.com/user-attachments/assets/fba284f7-dc8e-4fbe-ad11-7514cba58dc3

-blender 4.2
-windows 11

**Comment by PurgatoryMP** [comment]
I have updated the code to allow users to select the directory containing the image sequence directly. This will create a sprite sheet inside the image sequence directly.
