### ISSUE TITLE
Cannot bake floating point textures

### ISSUE THREAD

**Issue by bvz2000** [PurgatoryMP/Sequenced_Bake#3]
I need to be able to bake floating point images so that my baked textures can contribute to indirect lighting in optimized scenes.

In sequence_bake.py, line 915-916 you have this code:

```
texture = bpy.data.images.new(name=bake_type_name, width=image_width, height=image_height,
                                                  alpha=sequence_is_alpha)
```

I think it would be useful to add the following argument to this function call: 

`float=True`

Or, more specifically, something like `float=do_float` where `do_float` is defined via the user interface somewhere.

See this document for more info:

`https://docs.blender.org/api/current/bpy.ops.image.html`

Thanks!

**Comment by PurgatoryMP** [comment]
Hello,

Thank you for the suggestion, Any feedback is always appreciated.
I've added this option into the interface.
https://docs.blender.org/api/current/bpy.types.BlendDataImages.html

I've sent out an update 1.0.8 with the updated changes as well as a few other additions.
Please try this version and let me know if this works for you.
